# Generated by Django 4.1.3 on 2022-11-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="active",
        ),
    ]
